### ISSUE TITLE
Gradient opposed to UIColor

### ISSUE THREAD

**Issue by ingeniousgenius** [daltonclaybrook/tween-controller#6]
How could I use a gradient opposed to a UIColor?

**Comment by daltonclaybrook** [comment]
@jesster2k10 what aspects of the gradient are you trying to affect? Are you using a CAGradientLayer?

**Comment by daltonclaybrook** [comment]
I'm closing this issue. The answer is: yes, you can tween anything that conforms to `Tweenable`, and you can make your own types conform to `Tweenable`. For example, let's say you want to tween the `colors` property of `CAGradientLayer`. You could tween a particular instance of `UIColor` (which is already Tweenable), then in the action block, update the array of colors on the gradient:

```
func tweenGradient() {
    let gradientLayer = CAGradientLayer()
    controller
        .tween(from: UIColor.green, at: 0.0)
        .to(UIColor.blue, at: 1.0)
        .with { (color) in
            gradientLayer.colors = [UIColor.clear, color]
    }
}
```
